[build]
  command = "npm run build"
  publish = "dist"
  node_version = "22.20.0"
[[headers]]
  for = "/*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"

[[headers]]
  for = "/*.gltf"
  [headers.values]
    Content-Type = "model/gltf+json"
